/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-secondary': 'var(--color-on-secondary)',
        'surface-tint': 'var(--color-surface-tint)',
        'surface-dim': 'var(--color-surface-dim)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'error': 'var(--color-error)',
        'outline': 'var(--color-outline)',
        'primary': 'var(--color-primary)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'surface-container': 'var(--color-surface-container)',
        'tertiary': 'var(--color-tertiary)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'on-error': 'var(--color-on-error)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'error-container': 'var(--color-error-container)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'on-background': 'var(--color-on-background)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'outline-variant': 'var(--color-outline-variant)',
        'on-surface': 'var(--color-on-surface)',
        'on-primary': 'var(--color-on-primary)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'surface-variant': 'var(--color-surface-variant)',
        'secondary': 'var(--color-secondary)',
        'surface': 'var(--color-surface)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-bright': 'var(--color-surface-bright)',
        'on-error-container': 'var(--color-on-error-container)',
        'background': 'var(--color-background)',
        'primary-container': 'var(--color-primary-container)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'surface-container-low': 'var(--color-surface-container-low)',
      },
      fontFamily: {
        'headline': ['var(--font-headline)'],
        'display': ['var(--font-display)'],
        'body': ['var(--font-body)'],
        'label': ['var(--font-label)'],
        'mono': ['var(--font-mono)'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
